const std = @import("std");

pub const WORDS = [_][]const u8{
    "moonwalking",
    "beaming",
    "pursuing",
    "zigzagging",
    "drifting",
    "gliding",
    "wandering",
    "roaming",
    "spiraling",
    "hovering",
    "flickering",
    "shimmering",
    "echoing",
    "pulsing",
    "cascading",
    "orbiting",
    "meandering",
    "phasing",
    "blinking",
    "streaking",
    "vaulting",
    "slipping",
    "skimming",
    "floating",
    "rippling",
    "oscillating",
    "darting",
    "sliding",
    "rolling",
    "weaving",
    "flowing",
    "sweeping",
    "bursting",
    "charging",
    "flaring",
    "bouncing",
    "skipping",
    "tracing",
    "looping",
    "tilting",
    "tumbling",
    "glimmering",
    "warping",
    "cruising",
    "ghosting",
    "morphing",
    "phantoming",
    "bobbing",
    "lunging",
    "stalking",
    "creeping",
    "prowling",
    "surging",
    "flashing",
    "glancing",
    "sidestepping",
    "sidling",
    "zigging",
    "zagging",
    "pivoting",
    "arcing",
    "swooping",
    "dipping",
    "fluttering",
    "skittering",
    "scampering",
    "shuffling",
    "peeking",
    "peering",
    "flicking",
    "twisting",
    "coiling",
    "uncoiling",
    "threading",
    "streaming",
    "jetting",
    "blooming",
    "glowing",
    "radiating",
    "scanning",
    "tracking",
    "homing",
    "locking",
    "unlocking",
    "syncing",
    "desyncing",
    "buffering",
    "hopping",
    "bounding",
};

pub const MAX_LEN: u16 = blk: {
    var max: u16 = 0;
    for (WORDS) |w| {
        if (w.len > max) max = @intCast(w.len);
    }
    break :blk max;
};

pub fn chooseIndex(now_ms: u64, salt: []const u8) usize {
    var buf: [8]u8 = undefined;
    std.mem.writeInt(u64, &buf, now_ms, .little);
    const h1 = std.hash.Wyhash.hash(0, buf[0..]);
    const h2 = std.hash.Wyhash.hash(h1, salt);
    return @intCast(h2 % WORDS.len);
}
